simple: This is a simple message
message:
  welcome: Welcome to built in property file
  goodbye: Goodbye from built in property file
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
  endpoint:
    env:
      show-values: ALWAYS

logging:
  level:
    org:
      springframework:
        cloud: DEBUG